### ISSUE TITLE
建议标题支持左/右对齐

### ISSUE THREAD

**Issue by abc1763613206** [nanmu42/orly#2]
如题。

**Comment by nanmu42** [comment]
这个点子不错，谢谢反馈。😀

对齐支持：左，中，右
非CJK时降低字号。

**Comment by abc1763613206** [comment]
另外可以添加自定义上传图片功能。

**Comment by nanmu42** [comment]
哈哈，最后优化了下，纯英文时会有更小的字号。
左对齐右对齐暂时不搞了。

谢谢你的反馈！ :beers:
