### ISSUE TITLE
Error 525

### ISSUE THREAD

**Issue by rzfzr** [nanmu42/orly#28]
It is just me?
![image](https://user-images.githubusercontent.com/13456224/126344637-8d4009e2-f6ff-426e-9dc4-71abd9988e8f.png)

**Comment by nanmu42** [comment]
Opps, seems like a certificate issue, will look into it.

Thanks for notification!

**Comment by rzfzr** [comment]
No worries :D

**Comment by nanmu42** [comment]
I have updated my server certificate.

However, there seems to be some obstlcle in the network. For now, Error 525 may still occur occasionally. Try refreshing the page when in need.

Thank you.
