### ISSUE TITLE
image resolution

### ISSUE THREAD

**Issue by DennisCoder1024** [nanmu42/orly#3]
如果可以设置图片的分辨率就更好了

**Comment by nanmu42** [comment]
感谢你的反馈。😆

图片的分辨率和文件格式是多次尝试后的结果（分辨率不算小，文件不算大，编码时间相对短）。

使用 cmd 文件夹中的 drawer 可以自己定义图片大小和格式。

本地使用的话，相同分辨率下，gif格式的图片一般体积最小，质量也不错，不过编码时间最长。
