### ISSUE TITLE
[Feature Request]Share link

### ISSUE THREAD

**Issue by khjxiaogu** [nanmu42/orly#61]
Make a share function(Serialize all contents and output as base64 or something similiar).

**Comment by nanmu42** [comment]
Sharing on behalf of the website could bring some pressure on regulation compliance across countries and regions.

I suppose now there's no easy way to add this feature, sorry.

**Comment by khjxiaogu** [comment]
> Sharing on behalf of the website could bring some pressure on regulation compliance across countries and regions.
> 
> I suppose now there's no easy way to add this feature, sorry.
> 
> Thanks for your kind thought.

Just want to have a easier way to keep my design, without having to screenshot or copy the contents.
