### ISSUE TITLE
Long titles not supported

### ISSUE THREAD

**Issue by kirides** [nanmu42/orly#9]
Currently 
![image](https://user-images.githubusercontent.com/13602143/73937731-02826780-48e6-11ea-8efe-374495816d2d.png)

Expected:
- Fontsize reducing and / or line wrapping

**Comment by nanmu42** [comment]
Thanks for your feedback, I will look into this problem.

For now, linebreak and title font size are handled manually. So,

One line = bigger font
Two lines = smaller font

**Comment by Ahacad** [comment]
HI~ This problem seems to still exist, any plan to solve it?

**Comment by nanmu42** [comment]
For now there is no plan, but you can still use linebreak to fit long title manually. :p
