### ISSUE TITLE
Update frontend build tooling and dependencies

### ISSUE THREAD

**Issue by JessicaSachs** [nanmu42/orly#93]
As it stands, Node 16 is out of date and the Dockerfile isn't building. I got it working locally with Node 22 and pnpm. There's going to be a lot of churn + movement in the frontend package, is there any issue with this?

## Build + Environment Changes
- [ ] Update Node to latest LTS
- [ ] Update Dockerfile installation
- [ ] Update GitHub Actions image to latest Node LTS
- [ ] Swap to pnpm instead of yarn

## Frontend Build
After these infra updates, I'd like to upgrade to Vue 3 and Vite instead of Webpack. I'd also like to add TypeScript, if you don't mind.
- [ ] Vue 3 Upgrade
- [ ] Webpack => Vite

**Comment by nanmu42** [comment]
Cool, please do what you feel like to do. :)

Orly has been stale for a while, I am glad we have a new maintainer.

Please watch out for burnout and take your time. No need for any promise. Orly is a hobby project for fun, including the maintainer's.

**Comment by JessicaSachs** [comment]
Cool cool. I just didn't want to make too many changes or PRs and overwhelm you <3
